# Generated by Django 5.0.3 on 2024-04-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('endereco', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('disponibilidade', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=5)),
                ('experiencia', models.CharField(choices=[('sim', 'Sim'), ('não', 'Não')], max_length=3)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitação de voluntariado',
                'verbose_name_plural': 'Solicitações de voluntariado',
                'ordering': ['-data'],
            },
        ),
    ]
