# Generated by Django 5.0.3 on 2024-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castrado', models.CharField(choices=[('C', 'Castrado'), ('N', 'Não castrado')], default='N', max_length=1)),
                ('vacinas', models.CharField(max_length=200)),
                ('idas_vet', models.TextField()),
            ],
        ),
    ]
