# Generated by Django 5.0.3 on 2024-03-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='historico_saude',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animal.historicosaude'),
            preserve_default=False,
        ),
    ]
