# Generated by Django 5.0.3 on 2024-04-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_historico_saude'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
    ]
