# Generated by Django 5.0.3 on 2024-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_adotado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nome'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='historicosaude',
            options={'verbose_name': 'Histórico de saúde', 'verbose_name_plural': 'Histórico de saúde'},
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
