# Generated by Django 5.0.3 on 2024-04-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_animal_options_alter_hitoricosaude_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
